<a href="https://colab.research.google.com/github/snehalad/fundamentals-of-tensorflow/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction of tensorflow tf.constant()



In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# creating tensor tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check no of dimensions (ndim stands for number of dimentions)
scalar.ndim

0

In [ ]:
# create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create matrix (has more than 1 dimentions)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# creating other matrix
another_matrix = tf.constant([[12., 3.],
                              [13., 4.],
                              [15., 1.]], dtype=tf.float16) # specifydata type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12.,  3.],
       [13.,  4.],
       [15.,  1.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

🔖 what we learn here
* Scalar : a single number
* Vector : a number with direction (e.g wind speed and direction)
* matrix : 2-dimentional array of numbers
* tensor : an n-dimentional array of number
-> 0-dimensional tensor is scalar
-> 1 dimentional tensor is vector


### Creating tensor with tf.Variable()

In [ ]:
# create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeble_tensor = tf.constant([10, 7])
changeable_tensor, unchangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# let's try to change value of changeable variable
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# let's try to change unchangeble tensor
unchangeble_tensor[0].assign(7)

AttributeError: ignored

**🔑Note**: You have to decide whether to use `tf.constant` or `tf.Variable` to create tensor. However if in doubt, use `tf.constant` and change it later if needed

### Creating Random Tensor
Ramdom tensor are tensors of some abitrary size which contain random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set Seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) 
random_2 = random_2.normal(shape=(3,2))

# Are ty equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**🔑Note:** There are many ways to create random tensor like `tf.random.uniform` `tf.random.normal` `tf.random.Generator`. Here as we create random tensor it is a sudo random tensor as we see.





### Shuffle the order of element in a tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so inherent can't affect)
not_shuffle = tf.constant([[10, 7],
                     [7, 10],
                     [2, 5]])
# shuffle our non_shuffle tensor
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
# shuffle our non_shuffle tensor
# tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffle) # opertion level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 7, 10],
       [10,  7]], dtype=int32)>

It looks like we want our shuffled tensors to be in the same order, we have to use global as well as operational level random seed.
> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Creating tensor with Num py
The differnce between Numpy array and tensorflow tensor is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# create a tesnor of all ones
tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# creating a tensor of all zeros
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Turn numpy into tensor
import numpy as np

num_A = np.arange(1, 25, dtype=np.int32)
num_A = tf.constant(num_A, shape=[2, 3, 4])
num_A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors
Attributes
- shape -> tensor.shape
- rank -> tensor.ndim
- Axis / dimention -> tesnor[0], tesnor[:, 1]
- size -> tf.size(tesnor) 

In [ ]:
# creating rank_4 tesnsors(4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Dtatatype of evry element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along the 0 axis:", rank_4_tensor.shape[0])
print("Element along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Dtatatype of evry element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Element along the last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


### Indexing Tensors
tensors can be indexed just like python list

In [ ]:
# get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor(2 dimensional)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# get last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# add in eatra dimension to our rank2 tensoe
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # expand at 0 dimension

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic Operatons**
`+`, `-`, `*`, `/`

In [ ]:
# add values to a tensor using the addition operatoe
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# tensor build in math fuction
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

**Rules of Matrix Multiplication:**
  1. The inner dimensions must match
  2. The resulting matrix has the shape of the outer dimensions
  3. m * `n`  ✖  `n` * p ↪ m * p

📖**Resource**: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# matrix multiplication tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# create tensor(3,2)
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# create tensor(3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# let's reshape y
tf.reshape(y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [ ]:
# try matrix multiply same shape
tf.matmul(x, y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# try chnage the shape of x
tf.matmul(tf.reshape(x, shape=(2, 3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Using traspose
x = tf.transpose(x)
x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

**Dot Product**

Matrix multiplication also referred as dot product.

matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
# create tensor(3,2)
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# create tensor(3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# perform dot products on x and y (requires x or y to be trasposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**🔑Note:** while doing matrix multiplication on two tensor and one of the axes dons't line up, you will transpose(rather than reshape) of tensor to satisfy rules of matrix multiplication rules.

### changing the Datatype of a tensor

`tf.cast`

In [ ]:
# create new tensor with default dtype
B = tf.constant([1.4, 1.7])
B.dtype

tf.float32

In [ ]:
C = tf.constant([2, 4])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 (reduse precision)
B = tf.cast(B, dtype=tf.float16)
print(B)

C = tf.cast(C, dtype=tf.int16)
print(C)

tf.Tensor([1.4 1.7], shape=(2,), dtype=float16)
tf.Tensor([2 4], shape=(2,), dtype=int16)


### Aggregating tensors

Aggregating tensor = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# get absoulate value (neg to positive)
s = tf.constant([-6, -8])
s

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-6, -8], dtype=int32)>

In [ ]:
tf.abs(s)   

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8], dtype=int32)>


Let's go through the following forms of aggregation:

* Minumum `tf.reduce_min()`
* Maximum `tf.reduce_max()`
* Mean of tensor `tf.reduce_mean()`
* Sum of tensor `tf.reduce_sum()`
* Variance `tf.math.reduce_variance()`
* Standard Deviation `tf.math.reduce_std`

In [ ]:
# create tensor
a_tensor = tf.constant([10, 90])
b_tensor = tf.constant([115])
a_tensor, b_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 90], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([115], dtype=int32)>)

In [ ]:
# Minimum 
print("Minimum from single tensor", tf.reduce_min(a_tensor))
print("Minimum from two tensors", tf.minimum(a_tensor, b_tensor))

Minimum from single tensor tf.Tensor(10, shape=(), dtype=int32)
Minimum from two tensors tf.Tensor([10 90], shape=(2,), dtype=int32)


In [ ]:
# maximum
print("Maximum from singletensor", tf.reduce_max(a_tensor))
print("Maximum from two tensor", tf.maximum(a_tensor, b_tensor))

Maximum from singletensor tf.Tensor(90, shape=(), dtype=int32)
Maximum from two tensor tf.Tensor([115 115], shape=(2,), dtype=int32)


In [ ]:
# mean of the tensor
x_tensor = tf.constant([10, 5, 7, 18])
tf.reduce_mean(x_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Sum
print("Addition of single tensor\n", tf.reduce_sum(x_tensor))
print("Add two tensors:\n", tf.add(x_tensor, b_tensor))

Addition of single tensor
 tf.Tensor(40, shape=(), dtype=int32)
Add two tensors:
 tf.Tensor([125 120 122 133], shape=(4,), dtype=int32)


In [ ]:
# variance 
x = tf.constant([[1., 2.], [3., 4.]]) #  Should have real or complex type.
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [ ]:
# standard deviation
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.118034>

### Find the positional maximum and minimum

* `tf.argmax()`
* `tf.argmin()`

In [ ]:
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find positional maximum 
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check equality
assert f[tf.argmax(f)] == tf.reduce_max(f)

In [ ]:
# find positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# check equality
assert f[tf.argmin(f)] == tf.reduce_min(f)

### Squeezing a tensor (removing all single dimensions)

* `tf.squeeze` remove extra single dimentions

In [ ]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed = tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
g_squeezed.shape

TensorShape([50])

### One-hot encoding tensors

* `tf.one_hot()`

In [ ]:
# create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue etc

# one-hot encoding tensor
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="hello", off_value="sneha")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'sneha', b'sneha', b'sneha'],
       [b'sneha', b'hello', b'sneha', b'sneha'],
       [b'sneha', b'sneha', b'hello', b'sneha'],
       [b'sneha', b'sneha', b'sneha', b'hello']], dtype=object)>

### Tensor math operation

* Squaring `tf.square()`

🔑Note: for sqrt and log required non int values
* Square root `tf.sqrt()`
* log `tf.math.log`


In [ ]:
# create tensor
h = tf.range(1, 10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# square root (req non int values)
tf.sqrt(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# log (req non int values)
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interract beautifully with Numpy array

🔑**Note:** The main difference between a tensorflow tensor and numpy array ia that a tensorflow can run on GPU or TPU (for faster numerical processing)

In [ ]:
import numpy as np

# create tensor with numpy 
j = tf.constant(np.array([3., 7., 10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert tensor to numpy
np.array(j), type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor to numpy
j.numpy(), type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# data type of numpy array and tensor array slightly defferent
numpy_j = tf.constant(np.array([3., 7., 10.]))
tensor_j = tf.constant([3., 7., 10.])

# check the datatype of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

### Finding acess to GPUs

In [ ]:
import tensorflow as tf

tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Nov 28 12:05:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑**Note:** If you have access to a CUDA-enable GPU, Tensorflow will automatically use it whenever possible.